# Generated by Django 4.1.3 on 2022-11-26 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platocomida',
            name='image',
            field=models.ImageField(upload_to='platos_comida/'),
        ),
        migrations.AlterField(
            model_name='platocomida',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
