# Generated by Django 4.1.3 on 2022-12-10 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project_remove_carritocompra_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompra',
            name='cart',
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='cart',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
